<html>
    <head>
        <title><?= $this->headTitle;?></title>
        <meta charset="utf-8">
        <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.5.0/pure-min.css">
        <link rel="stylesheet" href="/css/default.css">
    </head>
    <body>
        <div class="pure-g container">
            <div class="pure-u-1-6 navigation">
                <?= $this->navigation ?>
            </div>
            <div class="pure-u-1-6"></div>
            <div class="pure-u-1-2">
                <div class="content">
                    <?= $this->content ?>
                </div>
            </div>
            <div class="pure-u-1-6"></div>
        </div>
    </body>
</html>