<div class="pure-menu pure-menu-open">
    <a href="<?= $this->url('dashboard');?>" class="pure-menu-heading">Dashboard</a>
    <a class="pure-menu-heading">Verwaltung</a>
    <ul>
        <li><a href="<?= $this->url('event');?>">Events verwalten</a></li>
        <li><a href="<?= $this->url('meal');?>">Speisen verwalten</a></li>
        <li><a href="<?= $this->url('user');?>">Mitglieder verwalten</a></li>
        <li><a href="<?= $this->url('donation');?>">Gutschriften verwalten</a></li>
    </ul>
    <a href="<?= $this->url('statistic');?>" class="pure-menu-heading">Statistiken</a>
    <ul>
        <li><a href="<?= $this->url('statistic', array('action' => 'highscore'));?>">Highscore</a></li>
        <li><a href="<?= $this->url('statistic', array('action' => 'events'));?>">Events</a></li>
        <li><a href="<?= $this->url('statistic', array('action' => 'cashBox'));?>">Die Kasse</a></li>
    </ul>
</div>