<?php

$this->headTitle($title);
?>
    <h1><?php echo $this->escapeHtml($title); ?></h1>
<?php

$form->setAttribute('action', $actionPath);
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formRow($this->form->get('id'));
echo $this->formRow($this->form->get('name'));
echo $this->formRow($this->form->get('date'));

echo $this->formCollection($this->form->get('consumptions'));
?>
<button class="pure-button pure-button-primary" onclick="return add_category()">Neu</button>
<?php
echo $this->formHidden($form->get('security'));
echo $this->formElement($form->get('submit'));
$this->form()->closeTag();
?>

<script type="text/javascript">
    function add_category() {
        var currentCount = $('form > fieldset > fieldset').length;
        var template = $('form > fieldset > span').data('template');
        template = template.replace(/__placeholder__/g, currentCount);

        $('form > fieldset').append(template);

        return false;
    }
</script>
