<?php use Event\Doctrine\Orm\Event;

$this->headTitle($title); ?>
<h2>
    <?=$title; ?>
</h2>
<?php
$class = isset($options['class']) ? ' '.$options['class'] : null
/** @var Event[] $events */
?>


<div class="expandable-list<?=$class;?>">
    <?php foreach ($events as $event) : ?>
        <div class="pure-g expandable-item">
            <div class="pure-u-1">
                <div class="pure-g expandable-head">
                    <div class="pure-u-1-2">
                        <?=$event->getName()?> &nbsp;
                        <a
                            href="<?=$this->url('event', array('action' => 'edit', 'id' => $event->getId())) ;?>"
                            title="<?=$event->getName()?> Bearbeiten">
                            Bearbeiten
                        </a>
                    </div>
                    <div class="pure-u-1-2">
                        Preis (komplett): <button class="button-warning"><?=round($event->getPriceInComplete()/100, 2)?> €</button>
                        Außenstände: <button
                            class="<?= ($event->isBalanced() ? 'button-success' : 'button-error') ?>">
                            <?= round($event->getReceivables()/100, 2)?> €
                            </button>
                    </div>
                </div>
            </div>
            <div class="pure-u-1">
                <div class="pure-g expandable-body">
                    <div class="pure-u-1-2">
                    <h3>Liste der Bestellungen</h3>
                    <ul>
                        <?php foreach ($event->getConsumptions()->toArray() as $consumption) : ?>
                            <li class="pure-g">
                                <div class="pure-u-1-6">
                                    <?=$consumption->getUser()->getUsername() ?>
                                </div>
                                <div class="pure-u-1-2">
                                    <?= $consumption->getAmountOf() ?> x <?= $consumption->getMeal()->getName() ?>
                                </div>
                                <div class="pure-u-1-3">
                                    Offen: <button
                                        class="<?= ($consumption->isBalanced() ? 'button-success' : 'button-error') ?>"
                                        >
                                        <?=round($consumption->getReceivables()/100, 2) ?> €
                                    </button>
                                </div>
                            </li>
                        <?php endforeach; ?>
                    </ul>
                </div>
                    <div class="pure-u-1-2">
                        <h3>Einkaufsliste:</h3>
                        <ul>
                            <? foreach( $meals[$event->getId()] as $meal) : ?>
                                <li>
                                    <?=$meal['count']?> X <?=$meal['name']?>
                                    <?=round($meal['count']*$meal['price']/100, 2)?> €
                                </li>
                            <?php endforeach; ?>
                        </ul>
                    </div>
            </div>
            </div>
        </div>
    <?php endforeach; ?>
</div>