<?php

$title = 'Neue Speise hinzufügen';
$this->headTitle($title);
?>
    <h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form->setAttribute('action', $this->url('meal', array('action' => 'add')));
$form->prepare();

echo $this->form()->openTag($form, array('class' => 'pure-form'));
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('name'));
echo $this->formRow($form->get('price'));
echo $this->formRow($form->get('description'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();